void AddAeonusSoloRaidScripts();
void AddAnubarakTrialSoloRaidScripts();
void AddAssemblyOfIronSoloRaidScripts();
void AddAuriayaSoloRaidScripts();
void AddBrutallusSoloRaidScripts();
void AddChromaggusSoloRaidScripts();
void AddEbonrocSoloRaidScripts();
void AddFaerlinaSoloRaidScripts();
void AddFactionChampionsSoloRaidScripts();
void AddFathomLordKarathressSoloRaidScripts();
void AddGluthSoloRaidScripts();
void AddGurtoggBloodboilSoloRaidScripts();
void AddHighKingMaulgarSoloRaidScripts();
void AddHighWarlordNajentusSoloRaidScripts();
void AddIllidanStormrageSoloRaidScripts();
void AddHodirSoloRaidScripts();
void AddKalecgosSoloRaidScripts();
void AddKelThuzadSoloRaidScripts();
void AddKaelthasSunstriderSoloRaidScripts();
void AddKazrogalSoloRaidScripts();
void AddKologarnSoloRaidScripts();
void AddLadyVashjSoloRaidScripts();
void AddLordJaraxxusSoloRaidScripts();
void AddMalygosSoloRaidScripts();
void AddMagtheridonSoloRaidScripts();
void AddMorogrimTidewalkerSoloRaidScripts();
void AddMountHyjalTrashSoloRaidScripts();
void AddMuruSoloRaidScripts();
void AddNetherspiteSoloRaidScripts();
void AddPatchwerkSoloRaidScripts();
void AddRazorgoreTheUntamedSoloRaidScripts();
void AddRazorscaleSoloRaidScripts();
void AddReliquaryOfSoulsSoloRaidScripts();
void AddRazuviousSoloRaidScripts();
void AddSunwellPlateauTrashSoloRaidScripts();
void AddThaddiusSoloRaidScripts();
void AddTemporusSoloRaidScripts();
void AddThorimSoloRaidScripts();
void AddTwinEmperorsSoloRaidScripts();
void AddUlduarTrashSoloRaidScripts();
void AddVaelastraszTheCorruptSoloRaidScripts();
void AddXT002SoloRaidScripts();
void AddYoggSaronSoloRaidScripts();

void Addmod_solo_raidsScripts()
{
    AddAeonusSoloRaidScripts();
    AddAnubarakTrialSoloRaidScripts();
    AddAssemblyOfIronSoloRaidScripts();
    AddAuriayaSoloRaidScripts();
    AddBrutallusSoloRaidScripts();
    AddChromaggusSoloRaidScripts();
    AddEbonrocSoloRaidScripts();
    AddFaerlinaSoloRaidScripts();
    AddFactionChampionsSoloRaidScripts();
    AddFathomLordKarathressSoloRaidScripts();
    AddGluthSoloRaidScripts();
    AddGurtoggBloodboilSoloRaidScripts();
    AddHighKingMaulgarSoloRaidScripts();
    AddHighWarlordNajentusSoloRaidScripts();
    AddIllidanStormrageSoloRaidScripts();
    AddHodirSoloRaidScripts();
    AddKalecgosSoloRaidScripts();
    AddKelThuzadSoloRaidScripts();
    AddKaelthasSunstriderSoloRaidScripts();
    AddKazrogalSoloRaidScripts();
    AddKologarnSoloRaidScripts();
    AddLadyVashjSoloRaidScripts();
    AddLordJaraxxusSoloRaidScripts();
    AddMalygosSoloRaidScripts();
    AddMagtheridonSoloRaidScripts();
    AddMorogrimTidewalkerSoloRaidScripts();
    AddMountHyjalTrashSoloRaidScripts();
    AddMuruSoloRaidScripts();
    AddNetherspiteSoloRaidScripts();
    AddPatchwerkSoloRaidScripts();
    AddRazorgoreTheUntamedSoloRaidScripts();
    AddRazorscaleSoloRaidScripts();
    AddReliquaryOfSoulsSoloRaidScripts();
    AddRazuviousSoloRaidScripts();
    AddSunwellPlateauTrashSoloRaidScripts();
    AddThaddiusSoloRaidScripts();
    AddTemporusSoloRaidScripts();
    AddThorimSoloRaidScripts();
    AddTwinEmperorsSoloRaidScripts();
    AddUlduarTrashSoloRaidScripts();
    AddVaelastraszTheCorruptSoloRaidScripts();
    AddXT002SoloRaidScripts();
    AddYoggSaronSoloRaidScripts();
}
