void AddAeonusSoloRaidScripts();
void AddBrutallusSoloRaidScripts();
void AddChromaggusSoloRaidScripts();
void AddEbonrocSoloRaidScripts();
void AddFathomLordKarathressSoloRaidScripts();
void AddGluthSoloRaidScripts();
void AddGurtoggBloodboilSoloRaidScripts();
void AddHighKingMaulgarSoloRaidScripts();
void AddHighWarlordNajentusSoloRaidScripts();
void AddIllidanStormrageSoloRaidScripts();
void AddKalecgosSoloRaidScripts();
void AddKelThuzadSoloRaidScripts();
void AddKaelthasSunstriderSoloRaidScripts();
void AddKazrogalSoloRaidScripts();
void AddLadyVashjSoloRaidScripts();
void AddMagtheridonSoloRaidScripts();
void AddMorogrimTidewalkerSoloRaidScripts();
void AddMountHyjalTrashSoloRaidScripts();
void AddMuruSoloRaidScripts();
void AddNetherspiteSoloRaidScripts();
void AddPatchwerkSoloRaidScripts();
void AddRazorgoreTheUntamedSoloRaidScripts();
void AddReliquaryOfSoulsSoloRaidScripts();
void AddRazuviousSoloRaidScripts();
void AddSunwellPlateauTrashSoloRaidScripts();
void AddThaddiusSoloRaidScripts();
void AddTemporusSoloRaidScripts();
void AddTwinEmperorsSoloRaidScripts();
void AddVaelastraszTheCorruptSoloRaidScripts();

void Addmod_solo_raidsScripts()
{
    AddAeonusSoloRaidScripts();
    AddBrutallusSoloRaidScripts();
    AddChromaggusSoloRaidScripts();
    AddEbonrocSoloRaidScripts();
    AddFathomLordKarathressSoloRaidScripts();
    AddGluthSoloRaidScripts();
    AddGurtoggBloodboilSoloRaidScripts();
    AddHighKingMaulgarSoloRaidScripts();
    AddHighWarlordNajentusSoloRaidScripts();
    AddIllidanStormrageSoloRaidScripts();
    AddKalecgosSoloRaidScripts();
    AddKelThuzadSoloRaidScripts();
    AddKaelthasSunstriderSoloRaidScripts();
    AddKazrogalSoloRaidScripts();
    AddLadyVashjSoloRaidScripts();
    AddMagtheridonSoloRaidScripts();
    AddMorogrimTidewalkerSoloRaidScripts();
    AddMountHyjalTrashSoloRaidScripts();
    AddMuruSoloRaidScripts();
    AddNetherspiteSoloRaidScripts();
    AddPatchwerkSoloRaidScripts();
    AddRazorgoreTheUntamedSoloRaidScripts();
    AddReliquaryOfSoulsSoloRaidScripts();
    AddRazuviousSoloRaidScripts();
    AddSunwellPlateauTrashSoloRaidScripts();
    AddThaddiusSoloRaidScripts();
    AddTemporusSoloRaidScripts();
    AddTwinEmperorsSoloRaidScripts();
    AddVaelastraszTheCorruptSoloRaidScripts();
}
